### ISSUE TITLE
Throws exception during launch when Screeps is installed on another drive other than C:\

### ISSUE THREAD

**Issue by nrnoble** [laverdet/screeps-steamless-client#1]
I have Steam and Screeps installed on an application\data drive, drive D:\.

Execute: **npx screeps-steamless-client**

Result:
```
[Error: ENOENT: no such file or directory, open 'C:\Program Files (x86)\Steam\steamapps\common\Screeps\package.nw'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Program Files (x86)\\Steam\\steamapps\\common\\Screeps\\package.nw'
}
```

from src: 

```
const [ data, stat ] = await async function() {
	const path = argv.package ?? function() {
		switch (process.platform) {
			case 'darwin': return new URL('./Library/Application Support/Steam/steamapps/common/Screeps/package.nw', `${pathToFileURL(os.homedir())}/`);
			case 'win32': return 'C:\\Program Files (x86)\\Steam\\steamapps\\common\\Screeps\\package.nw';
			default: return undefined;
		}
```

**Comment by laverdet** [comment]
You can pass the `--package` command line argument to specify the location of the package

**Comment by nrnoble** [comment]
I can't seem to get the correct command line syntax. Could you provide an example of how the `--package` should be used if the SteamLibrary is located at `D:\SteamLibrary.` Thanks!

**Comment by laverdet** [comment]
I would guess something like: npx screeps-steamless-client --package "D:\SteamLibrary\Screeps\package.nw"

You would have to figure out where that file is, and pass it as an argument.

**Comment by nrnoble** [comment]
Thanks for tip. In my case, Steam created the games directory on D as follows

D:\SteamLibrary\steamapps\common\Screeps

thus, this command work

npx screeps-steamless-client --package "D:\SteamLibrary\steamapps\common\Screeps\package.nw"

**Comment by nrnoble** [comment]
the use of `--package` solves the issue.

**Comment by tianyma** [comment]
> the use of `--package` solves the issue.

what if I want to use this client to connect xxscreeps, where can I find the package.nw?

**Comment by bastianh** [comment]
It's the same. For both, this project and xxscreeps-client, you need to buy the screeps client on steam.

This project and xxscreeps-client are only helper to run it without starting it from steam and run it in a browser. The main reason they were crestad is because the steam client does not work correctly on Mac otherwise.

**Comment by tianyma** [comment]
> It's the same. xxscreeps uses the same client as screeps and the client is payware. For both, this project and xxscreeps-client, you need to buy the screeps client on steam.
> 
> This project and xxscreeps-client are only helper to run it without starting it from steam and run it in a browser. The main reason they were crestad is because the steam client does not work correctly on Mac otherwise.

I see it, can you tell me what exactly package.nw is, why should I give it as an argument when start the client?
