### ISSUE TITLE
could not find pacakge.nw

### ISSUE THREAD

**Issue by Sult** [laverdet/screeps-steamless-client#20]
hello,
after a fresh install of the package, or from the repository I am getting the following error

I am not very proficient with npm so probably i am missing something easy

```
npx screeps-steamless-client
Could not find `package.nw`. Please check `--package` argument
```

**Comment by bastianh** [comment]
You are missing the screeps client. You have to buy it.

This package allows to run it without steam, but you still have to install it.

**Comment by Sult** [comment]
hoped it was open source too haha. but bought it. closing ticket
